version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      SA_PASSWORD: "YourStrong@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  web:
    image: hoanvu2/trinhhoanvu
    container_name: my_web_app
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=ShopDB;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: YourStrong@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.SQLServerDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  sql_data:
